### ISSUE TITLE
Move YouTube player to lightbox in page template

### ISSUE THREAD

**Issue by matticoli** [jazzhistorydatabase/jhdb-cms#107]
This will prevent iframe loading from slowing down page load times on slower internet connections

**Comment by drnek** [comment]
This will improve page load speed, user engagement and SEO (due to page load speed)

**Comment by matticoli** [comment]
If we wanted to further optimize, we could have preview image with play button generated on publish, so all images are loaded on the same place, but this would only matter once #94 is addressed

**Comment by drnek** [comment]
yes it could be generated when the file is linked and saved, so the preview works

**Comment by matticoli** [comment]
Videos are currently not linked as files, we do some string processing on the url to make sure it is in the correct format and generate an embed code

**Comment by drnek** [comment]
it's fine if videos are not linked as files, but the YouTube API allows it.  https://developers.google.com/youtube/v3/docs/thumbnails

**Comment by matticoli** [comment]
Right, I meant there isn't really a "link" step for videos like there is for images and audio files

**Comment by drnek** [comment]
Let’s make the play button 150px on desktop and at least 100px on mobile

**Comment by drnek** [comment]
looks great, I would make the play button bright blue and 2X as large (overlay button)
