### ISSUE TITLE
Review and update page format for output page HTML - correct display errors

### ISSUE THREAD

**Issue by drnek** [jazzhistorydatabase/jhdb-cms#110]
Need to do a full review of all code output for the collection pages.

- images should not have overlay shadow on hover to get a larger image in Lightbox. this also has a secondary bug we'll remove which is that the circle inside needs to be clicked and is missing the icon.  user needs to be able to click anywhere on the image to bring larger image up in lighbox.
- header is from a collection made incorrectly where the menu bar should have a white gap above it until scrolled down to enable sticky.  this is a primary container issue.
- images should be shown by default in a larger gallery, smaller font, etc.. 
- bio photo format should have border, maybe rounded corners. look at size of image
- scroll to top icon on bottom is broken

**Comment by matticoli** [comment]
@drnek Are these bugs appearing in preview or in published pages? Header include works slightly differently in preview vs published output

**Comment by drnek** [comment]
full screen preview but it's not the header I'm talking about it's the nav menu of the collection. some collections were built incorrectly over the past 2 years by whomever and that code was evidently copied for this template.  above the nav bar for the collection title and pages should be 60px or so of space until they scroll down when the space goes to sticky and joins the above nav menu.  check http://www.jazzhistorydatabase.com/archives/david-kidd/

**Comment by matticoli** [comment]
This is a good reference, thanks! It looks good on mobile too except for the audio player styles

**Comment by drnek** [comment]
still need a gap between the menu bars so the main page structure needs review.

this one has the correct structure for the nav menu and containers. 
http://www.jazzhistorydatabase.com/archives/ben-young/index.php
