### ISSUE TITLE
Link URL title

### ISSUE THREAD

**Issue by drnek** [jazzhistorydatabase/jhdb-cms#113]
links need titles, like this:

`<a href="https://www.w3schools.com/html/" title="Go to W3Schools HTML section">Visit our HTML Tutorial</a>`

any links to media files, audio video or images should have titles.  use hyphenated non-funky% caption data

**Comment by drnek** [comment]
looks like this one is still open

**Comment by matticoli** [comment]
Issues get closed when deployed to master I think
