### ISSUE TITLE
Shadowbox bug

### ISSUE THREAD

**Issue by matticoli** [jazzhistorydatabase/jhdb-cms#127]
fix shadowbox bug and remove the overlay. take a basic shadowbox style from template. not from a portfolio page like as is now, where they have to click the center of an empty circle to get a larger image.

ideally we would disable shadowbox for source images less than 800px max dim

**Comment by drnek** [comment]
yes we def need to disable shadowbox for images under 800px, otherwise it's very disappointing lol.. 
should we add this as a new bug?

**Comment by matticoli** [comment]
> yes we def need to disable shadowbox for images under 800px, otherwise it's very disappointing lol.. 
> should we add this as a new bug?

How should the smaller images be displayed if not with shadowbox? The template doesn't know the size of the image and ux should be consistent
