### ISSUE TITLE
Multiple FileUpload components can be bound to the same Firebase doc

### ISSUE THREAD

**Issue by LucasNVarella** [jazzhistorydatabase/jhdb-cms#21]
Sometimes multiple added FileUploads (be it an image, audio, or video) will all be bound to the same Firebase doc. The correct number of docs are created, but all multiple FileUploads seem to be bound to the latest doc created, This does not always happen - it may have to do with the speed at which FileUploads are added.

**Comment by matticoli** [comment]
Resolved in #26
