### ISSUE TITLE
Lock changes to a contribution while pending admin approval

### ISSUE THREAD

**Issue by LucasNVarella** [jazzhistorydatabase/jhdb-cms#71]
Currently, a contributor may make changes to a contribution while said contribution is pending approval. We want to make sure contributors cannot make changes to contributions that are pending approval. They should have to remove their request for approval (flip the switch back in the edit contribution page) before making changes, to preserve our workflow

**Comment by matticoli** [comment]
We should also lock changes on published contributions until #27 is implemented so live contributions can't be edited
