### ISSUE TITLE
Disable the About JHDB Modal for previews

### ISSUE THREAD

**Issue by LucasNVarella** [jazzhistorydatabase/jhdb-cms#96]
We can't just delete the modal from the template either, as we will need it and its php code to work in production.

**Comment by drnek** [comment]
disable for anyone logged in

**Comment by matticoli** [comment]
The preview header is different from the prod header (as the former is included via js and the latter is included via php). If we are keeping with this, removing the popup in the portal code may be the easiest solution

Alternatively, we may want to move towards including the global prod header in the preview template

**Comment by drnek** [comment]
Using the global production header in the preview template should also allow us to include Google analytics tracking.

**Comment by drnek** [comment]
Otherwise, removing the pop-up entirely from the global contributor portal would be perfect

**Comment by matticoli** [comment]
Do we want Google Analytics enabled for previews in the contributor portal? I would say probably not. We do want them enabled in production though

**Comment by drnek** [comment]
it would be interesting to see users around the world contributing in google analytics, but not required.  otherwise we see viewers only, which is normal.

**Comment by matticoli** [comment]
I mean we will see when they visit the page at global.jazzhistorydatabase.com. It will just be disabled in the portal so we don't get false view stats everytime someone clicks preview
