### ISSUE TITLE
Unpublish flow through UI

### ISSUE THREAD

**Issue by LucasNVarella** [jazzhistorydatabase/jhdb-cms#97]
Currently unpublishing a collection is a manual process. Flipping the switch to unpublish a collection in the EditContribution page currently does nothing. Re-publishing after unpublishing from the UI may result in unexpected behavior.
If users are not intended to be able to unpublish through the UI, we should disable the switches once a collection is published.

**Comment by matticoli** [comment]
This is intended behavior. Republishing updates appropriately and does not cause any bugs. Deleting files in Dropbox from the portal is a security hazard, and it is reasonable to require that that be done by a global administrator on special occasions only (as the page would also need to be un-linked from the frontpage anyway)
